### ISSUE TITLE
Frameskip

### ISSUE THREAD

**Issue by Jeff-Bootonic** [krabobmkd/amigamame#6]
A frameskip option would be great.
Maybe with the option to choose between individual steps and automatic mode.

**Comment by krabobmkd** [comment]
Hello.
With emulation, skipping half the frames will not gain 50% speed, it will actually gain around 10% or 5% speed, because your 68k cpu emulating resource are used like: 60% taken to emulate cpu + 20% taken to emulate sound + 20% to emulate video.) Frameskip consists in "not emulating video" for a given frame, but you can't escape 80% of the work for frames you will not see.
 So there will be a "display half the frame on 2." options, but no automatic frameskip.
Optimisation will always be a better solution.

**Comment by krabobmkd** [comment]
Fun thing to do: When you pause with "P" and display the speed stats with "Help", what MAME does is "stop to emulate CPU and sound, but continue to emulate video chip." ; This  gives an interesting information on how much of the emulation is used for CPU and video.
